### PR TITLE
Update installprocess to new documentation

### PR DESCRIPTION
**Pull request by solisinvictum**
See iv-org/invidious#2918 (comment)

and

https://github.com/iv-org/documentation/blob/master/Installation.md

### CODE REVIEW

**Comment by tmiland** [comment]
Thanks. 

No need to bump the version number though.

**Comment by solisinvictum** [comment]
Did this because like i see this determine if somebody get a update notification/new version.

And this change is critical for further usage. So that would be good if the user of the script get a new update.

**Comment by tmiland** [comment]
> Did this because like i see this determine if somebody get a update notification/new version.
> 
> And this change is critical for further usage. So that would be good if the user of the script get a new update.

The update will only trigger after i publish an update on GitHub, so there's no need for anyone other than me to increase that number.

**Comment by solisinvictum** [comment]
Isnt that a update? Anyways, feel free to change that.

Or should i create a new PR?

**Comment by tmiland** [comment]
> Isnt that a update? Anyways, feel free to change that.
> 
> Or should i create a new PR?

Just change back to 1.6.0 in this pull request and it's all good.

**Comment by solisinvictum** [comment]
Changed it like you wanted.

**Comment by tmiland** [comment]
LGTM 👍

**Pull request merged**
